#!/bin/sh

# A dmenu wrapper script for system functions.
#hello there
cmds="\
🔒 lock		slock
🚪 leave dwm	kill -TERM $(pidof -s dwm)
♻ renew dwm	kill -HUP $(pidof -s dwm)
🐻 hibernate	slock ${hib:-systemctl suspend-then-hibernate -i}
🔃 reboot	${reb:-reboot}
🖥 shutdown	${shut:-shutdown -h now}
📺 display off 	 xset dpms force off"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
